# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.11
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: haotrinh142@gmail.com
author_name: Trinhvhao
cloud_provider: none
contract_name: adv_marketplace
deployment_language: python
preset_name: production
project_name: adv-marketplace

